### ISSUE TITLE
pread returns EINVAL in linux

### ISSUE THREAD

**Issue by w41ter-l** [rust-lib-project/rocksdb-rs#7]
Run simple example in PR https://github.com/rust-lib-project/rocksdb-rs/pull/6: `cargo run --example simple_example`, and program will failed in `Engine::open`. The detail errno is EINVAL.

According to `man 2 read`:

> EINVAL fd  is attached to an object which is unsuitable for reading; or the file was opened with the O_DIRECT flag, and either the address specified in buf, the value specified in count, or the file offset is not suitably aligned.

I noticed that `get_current_manifest_path` will invokes `FileSystem::read_file_content`, which eventually invoke `AsyncRandomAccessFile::open`, and `O_DIRECT` is added to `open`, but there doesn't seem to be any alignment in `read_file_content`.

**Comment by Little-Wallace** [comment]
I have disable the direct io until someone could refactor the async file system to give read size alignment.
